spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
    devtools:
      livereload:
        enabled: true
      restart:
        enabled: true

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

scheduler:
  cron:
    member: "* * * * * *"
    study: "* * * * * *"

